- name: Configuring catalogue service
  hosts: catalogue
  become: yes
  tasks:
   - name: Disabling previous nodejs
     ansible.builtin.command: dnf module disable nodejs -y

   - name: Enabling nodejs v:20
     ansible.builtin.command: dnf module enable nodejs:20 -y

   - name: Installing nodejs
     ansible.builtin.dnf:
       name: nodejs
       state: present

   - name: Addding Roboshop User
     ansible.builtin.user:
       name: roboshop 
       shell: /sbin/nologin
       system: true
       home: /app

   - name: Creating app directory
     ansible.builtin.file:
       path: /app
       state: directory


   - name: Download app code
     ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip 
      dest: /tmp/catalogue.zip

   - name: Unziping code
     ansible.builtin.unarchive:
      src: /tmp/catalogue.zip
      dest: /app
      remote_src: yes

   - name: Installing dependencies
     community.general.npm:
       path: /app

   - name: Copying Catalogue.service files
     ansible.builtin.copy:
       src: catalogue.service
       dest: /etc/systemd/system/catalogue.service

   
   - name: Restart service after config changes
     ansible.builtin.systemd_service:
      daemon_reload: true
     
   - name: Starting and Enabling catalogue
     ansible.builtin.service:
      name: catalogue
      state: started
      enabled: yes
   
   - name: Copying mongo repos to install mongod client Server
     ansible.builtin.copy:
      src: mongodb.repo
      dest: /etc/yum.repos.d/mongo.repo

   - name: Install mongod client Server
     ansible.builtin.dnf:
       name: mongodb-mongosh
       state: installed

   - name: check products loaded or not
     ansible.builtin.command: mongosh --host mongodb.84dev.store --eval 'db.getMongo().getDBNames().indexOf("catalogue")'
     register: catalogue_output

   - name: print catalogue output
     ansible.builtin.debug:
        msg: "{{ catalogue_output }}"

   - name: load products
     ansible.builtin.command: mongosh --host mongodb.84dev.store < /app/db/master-data.js
     when: catalogue_output.stdout | int < 0
