- name: Configuring frontend server
  hosts: frontend
  become: yes
  tasks:
   - name: disable default nginx
     ansible.builtin.command: dnf module disable nginx -y  

   - name: enable nginx 1.24
     ansible.builtin.command: dnf module enable nginx:1.24 -y

   - name: installing nginx
     ansible.builtin.dnf:
      name: nginx
      state: present

   - name: Starting and Enabling nginx
     ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes

   - name: Removing default content from html
     ansible.builtin.file:
      src: /usr/share/nginx/html
      state: absent

   - name: Creating directory
     ansible.builtin.file:
      src: /usr/share/nginx/html
      state: directory
   
   - name: Downloading code
     ansible.builtin.get_url:
     url: https://roboshop-artifacts.s3.amazonaws.com/frontend-v3.zip
     dest: /tmp/frontend.zip

   - name: Unziping code
     ansible.builtin.unarchive:
      src: /tmp/frontend.zip
      dest: /usr/share/nginx/html

   - name: Copying content
     ansible.builtin.copy:
      src: nginx.conf
      dest: /usr/share/nginx/html

   - name: Restart nginx
     ansible.builtin.service:
      name: nginx
      state: restarted

    