- name: Configuring payment server
  hosts: payment
  become: yes
  tasks:
    - name: Installing python
      ansible.builtin.dnf:
       name: "{{ item }}"
       state: present
      loop:
       - python3 
       - gcc 
       - python3-devel

    - name: Addding user
      ansible.builtin.user:
       name: roboshop
       shell: /sbin/nologin
       system: true
       home: /app
    
    - name: Creating directory
      ansible.builtin.file:
       path: /app 
       state: directory

    - name: Downloading code
      ansible.builtin.get_url:
        url: https://roboshop-artifacts.s3.amazonaws.com/payment-v3.zip 
        dest: /tmp/payment.zip

    - name: Unziping files
      ansible.builtin.unarchive:
        src: /tmp/payment.zip
        dest: /app
        remote_src: yes
      
    - name: Installing dependencies
      ansible.builtin.pip:
       requriments: requirements.txt
      args:
        chdir: /app

    - name: Copying serv files
      ansible.builtin.copy:
        src: payment.service
        dest: /etc/systemd/system/payment.service

    - name: daemon_reload
      ansible.builtin.systemd_service:
       daemon_reload: true

    - name: Starting and Enabling payment
      ansible.builtin.service:
       name: payment
       state: started
       enabled: yes